<?php 

//nav menu keys
$HEADER_FULL_WIDTH_NAV_MENU_KEY = 'HEADER_FULL_WIDTH_NAV_MENU_KEY';
$HEADER_FIRST_BREAK_POINT_NAV_MENU_KEY = 'HEADER_FIRST_BREAK_POINT_NAV_MENU_KEY'; //1037-1132px
$HEADER_SECOND_BREAK_POINT_NAV_MENU_KEY = 'HEADER_SECOND_BREAK_POINT_NAV_MENU_KEY'; //992-1036px
$HEADER_MOBILE_NAV_MENU_KEY = 'HEADER_MOBILE_NAV_MENU_KEY';

$FOOTER_QUICK_LINKS_NAV_MENU_KEY = '$FOOTER_QUICK_LINKS_NAV_MENU_KEY';
$FOOTER_RENTALS_NAV_MENU_KEY = 'FOOTER_RENTALS_NAV_MENU_KEY';

//catagory IDs
$RENTALS = 6;
