<?php 

//nav menu keys
$HEADER_FULL_WIDTH_NAV_MENU_KEY = 'HEADER_FULL_WIDTH_NAV_MENU_KEY';
$FOOTER_QUICK_LINKS_NAV_MENU_KEY = '$FOOTER_QUICK_LINKS_NAV_MENU_KEY';
$FOOTER_RENTALS_NAV_MENU_KEY = 'FOOTER_RENTALS_NAV_MENU_KEY';